name: code_verification
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install pylint black

      - name: Run tests in parallel with coverage
        run: |
          pytest -v --cov=note_api --cov-report=xml --cov-report=html -n auto
      - name: Run Pylint
        run: |
          pylint .

      - name: Run Black Check
        run: |
          black --check .
