name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'hs-heilbronn-devsecops'

      - name: Pull Docker Image
        run: docker pull ghcr.io/hs-heilbron-devsecops-omega-oops/note-api:2024-11-19-15

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: 'note-api-hs-heilbronn-devsecops-omega-oops'
          image: 'ghcr.io/hs-heilbron-devsecops-omega-oops/note-api:2024-11-19-15'
          region: 'europe-west3'
          env_vars: BACKEND=memory
