name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0



      - name: Load configuration
        run: |
          echo "${{ secrets.CONFIG_JSON }}" | base64 --decode > config.json
          echo "service_name=$(jq -r '.service_name' config.json)" >> $GITHUB_ENV
          echo "region=$(jq -r '.region' config.json)" >> $GITHUB_ENV
          echo "artifact_registry=$(jq -r '.artifact_registry' config.json)" >> $GITHUB_ENV
          echo "env_vars=$(jq -r '.env_vars | tojson' config.json)" >> $GITHUB_ENV


      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          create_credentials_file: true


      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${{ env.artifact_registry }}


      - name: Build Docker image
        run: |
          docker build -t ${{ env.artifact_registry }}/note-api-hs-heilbron-devsecops-omega-oops:${{ github.sha }} .


      - name: Push Docker image
        run: |
          docker push ${{ env.artifact_registry }}/note-api-hs-heilbron-devsecops-omega-oops:${{ github.sha }}



      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.service_name }}
          image: ${{ env.artifact_registry }}/cloud-run-source-deploy/note-api:${{ github.sha }}
          region: ${{ env.region }}
          env_vars: ${{ env.env_vars }}
          ingress: all
