name: Deploy to Google Cloud Run

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Workflow Run Context
        run: |
            echo "Triggered by workflow: ${{ github.event.workflow_run.name }}"
            echo "Triggered workflow ID: ${{ github.event.workflow_run.id }}"
            echo "Triggered workflow run number: ${{ github.event.workflow_run.run_number }}"
            echo "Triggered workflow URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"

      - name: Download Image Name Artifact
        uses: actions/download-artifact@v4
        with:
          name: image-name
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Authenticate with GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin


      - name: Read Image Name
        run: |
          IMAGE_NAME=$(cat image-name.txt)
          echo "Using Image Name: $IMAGE_NAME"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
      

      - name: Load configuration
        run: |
          echo "${{ secrets.CONFIG_JSON }}" | base64 --decode > config.json
          echo "service_name=$(jq -r '.service_name' config.json)" >> $GITHUB_ENV
          echo "region=$(jq -r '.region' config.json)" >> $GITHUB_ENV
          echo "artifact_registry=$(jq -r '.artifact_registry' config.json)" >> $GITHUB_ENV
          echo "env_vars=$(jq -r '.env_vars | tojson' config.json)" >> $GITHUB_ENV
      

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Log GCP authentication success
        run: echo "Successfully authenticated with GCP."

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${{ env.service_name }} \
            --quiet \
            --image ${{ env.IMAGE_NAME }} \
            --update-env-vars "$(echo ${{ env.env_vars }} | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|join(",")')" \
            --platform managed \
            --region ${{ env.region }}

      - name: Get Cloud Run service details
        run: gcloud run services describe ${{ env.service_name }} --region ${{ env.region }}

      - name: Log Deployment Details
        run: |
          echo "Deployed image: ${{ env.IMAGE_NAME }}" > deployment.log
          echo "Service name: ${{ env.service_name }}" >> deployment.log
          echo "Region: ${{ env.region }}" >> deployment.log

      - name: Upload Deployment Log
        uses: actions/upload-artifact@v3
        with:
          name: deployment-log
          path: deployment.log