name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black bandit

      - name: Submit coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run Bandit to check for vulnerabilities
        run: bandit -r note_api/ -f json -o bandit_output.json || true

      - name: Upload Bandit report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit_output.json

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d")
          RUN_NUMBER=$(( $GITHUB_RUN_NUMBER % 1000 ))
          IMAGE_NAME="ghcr.io/${{ github.repository }}:$TIMESTAMP-$RUN_NUMBER"
          docker build -t $IMAGE_NAME .
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "$IMAGE_NAME" > image-name.txt

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ${{ env.IMAGE_NAME }}

      - name: Verify Image Name File
        run: |
            echo "Verifying image-name.txt"
            ls -l image-name.txt
            cat image-name.txt
      - name: Save Image Name to File
        run: echo "${{ env.IMAGE_NAME }}" > image-name.txt

      - name: Upload Image Name Artifact
        uses: actions/upload-artifact@v4
        with:
             name: image-name
             path: image-name.txt

      - name: Log Build Workflow Context
        run: |
            echo "Workflow Name: Build and Push Docker Image"
            echo "Workflow ID: ${{ github.run_id }}"
            echo "Workflow Run Number: ${{ github.run_number }}"
            echo "Workflow URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"